### ISSUE TITLE
nexus.stuartwarren.com is no more.

### ISSUE THREAD

**Issue by gdusbabek** [stuart-warren/logit#79]
Subject says it all. It looks like the domain expired.

Is there an alternate host that can be used?

**Comment by stuart-warren** [comment]
Sorry, don't remember getting notified about this ticket.
I moved DNS hosting providers and didn't get round to setting up the records, wasn't aware anyone else was using it :)
Will try and get it fixed up tonight!

**Comment by stuart-warren** [comment]
DNS is now resolving for me now that I've fixed it up
http://nexus.stuartwarren.com/nexus/content/repositories/snapshots/com/stuartwarren/logit/

Depending on where you are in the world it might take longer.
Do let me know either way.

**Comment by gdusbabek** [comment]
Works for me. Thanks for fixing this!
